# sources
source=~/.config/mango/monitors.conf
source=~/.config/mango/appearence.conf
source=~/.config/mango/animations.conf
source=~/.config/mango/input.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/keybinds.conf

exec-once=swaybg -i ~/.local/share/wallpapers/Pacifico,\ 2025\ Desktop\ Wallpaper.jpg
